# Introduction to Linear Algebra Assignment

Due by Sept 15, 2024

## Q1. Matrix Multiplication



In [1]:
import numpy as np

Create the following matrices in Numpy 

$$X = \begin{bmatrix}
2 & 3 & 4 \\
5 & 6 & 7
\end{bmatrix}$$

$$Y = \begin{bmatrix}
3 & 2  \\
5 & 6  \\
0 & 1 
\end{bmatrix}$$

In [2]:
# Complete your code here
X = np.array([[2, 3, 4], [5, 6, 7]])
print(X)
Y = np.array([[3,2], [5, 6],[0, 1]])
print(Y)

[[2 3 4]
 [5 6 7]]
[[3 2]
 [5 6]
 [0 1]]


Calculate $Z=XY$ (matrix mulitplication of $X$ and $Y$) by calculate each individual element of $Z$. Also calculate it with Numpy buildin function to confirm two answers are same.

In [3]:
Z = np.dot(X, Y) # write your code by replacing None with your code. Do not change the variable name Z
print(Z)

[[21 26]
 [45 53]]


In [4]:
# Write your code to calculate the Z manually here

Z1 = np.zeros((2,2)) #initialize the Z1 matrix
Z1[0, 0] = X[0, 0] * Y[0, 0] + X[0, 1] * Y[1, 0] + X[0, 2] * Y[2, 0]
#Your code should look like Z1[0,0] = 1*2 + 2*3+ 3*4 to reflect 
#the defintion of matrix mulitplication.
Z1[0, 1] = X[0, 0] * Y[0, 1] + X[0, 1] * Y[1, 1] + X[0, 2] * Y[2, 1]
Z1[1, 0] = X[1, 0] * Y[0, 0] + X[1, 1] * Y[1, 0] + X[1, 2] * Y[2, 0]
Z1[1, 1] = X[1, 0] * Y[0, 1] + X[1, 1] * Y[1, 1] + X[1, 2] * Y[2, 1]

print(Z1)

[[21. 26.]
 [45. 53.]]


In [5]:
# Re-Calculate Z using NumPy's dot function
Z = np.dot(X, Y)

print("NumPy calculation of Z:")
print(Z)

# Confirm the two results are the same
assert np.array_equal(Z1, Z), "The manual calculation and NumPy calculation do not match!"
print("Both calculations match!")

NumPy calculation of Z:
[[21 26]
 [45 53]]
Both calculations match!


### Q2 Use the property of matrices to prove properties of psudo inverse of matrices

The **pseudo-inverse** (or Moore-Penrose inverse) of a matrix is a generalization of the inverse matrix that can be applied to non-square or singular matrices, where a regular inverse does not exist.It is commonly used in linear algebra, statistics, and optimization for solving systems of linear equations, particularly when the system does not have a unique solution or is over- or under-determined.


The psudo inverse of a matrix $A$, denoted by $A^\dagger$, is defined as:

$$A^\dagger = (A^TA)^{-1}A^T$$

Let $A = \begin{bmatrix}
2 & 3 & 4 \\
5 & 6 & 7
\end{bmatrix}$. Write Python code to calculate $A^\dagger$

In [6]:
A = np.array([[2, 3, 4], [5, 6, 7]]) # define variable A.
print("Matrix A:")
print(A)

A_T = A.T
Adagger = np.linalg.inv(A_T @ A) @ A_T

Matrix A:
[[2 3 4]
 [5 6 7]]


LinAlgError: Singular matrix

Write your code to verify the following property of $A^\dagger$:

1. $AA^\dagger A = A$
2. $A^\dagger A A^\dagger = A^\dagger$
3. $(AA^\dagger)^T = AA^\dagger$
4. $(A^\dagger A)^T = A^\dagger A$


In [7]:
# Define matrix A
A = np.array([[2, 3, 4], [5, 6, 7]])
print("Matrix A:")
print(A)

# Calculate the pseudo-inverse using NumPy's pinv function
Adagger = np.linalg.pinv(A)
print("Pseudo-inverse of A:")
print(Adagger)

Matrix A:
[[2 3 4]
 [5 6 7]]
Pseudo-inverse of A:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]


In [8]:
# Define matrix A
A = np.array([[2, 3, 4], [5, 6, 7]])
print("Matrix A:")
print(A)

# Calculate the pseudo-inverse using NumPy's pinv function
Adagger = np.linalg.pinv(A)
print("Pseudo-inverse of A:")
print(Adagger)

# Calculate A A^\dagger A
A_Adagger_A = A @ Adagger @ A
print("A A^\dagger A:")
print(A_Adagger_A)

# Print A for comparison
print("Matrix A for comparison:")
print(A)

print("Matrix A matches A_Adagger_A")

Matrix A:
[[2 3 4]
 [5 6 7]]
Pseudo-inverse of A:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
A A^\dagger A:
[[2. 3. 4.]
 [5. 6. 7.]]
Matrix A for comparison:
[[2 3 4]
 [5 6 7]]
Matrix A matches A_Adagger_A


In [9]:
# Define matrix A
A = np.array([[2, 3, 4], [5, 6, 7]])
print("Matrix A:")
print(A)

# Calculate the pseudo-inverse using NumPy's pinv function
Adagger = np.linalg.pinv(A)
print("Pseudo-inverse of A:")
print(Adagger)

# Calculate A^\dagger A A^\dagger
Adagger_A_Adagger = Adagger @ A @ Adagger
print("A^\dagger A A^\dagger:")
print(Adagger_A_Adagger)

# Print A^\dagger for comparison
print("Pseudo-inverse of A for comparison:")
print(Adagger)

print("Psuedo-inverse of A matches Adagger_A_Adagger")

Matrix A:
[[2 3 4]
 [5 6 7]]
Pseudo-inverse of A:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
A^\dagger A A^\dagger:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
Pseudo-inverse of A for comparison:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
Psuedo-inverse of A matches Adagger_A_Adagger


In [10]:
# Define matrix A
A = np.array([[2, 3, 4], [5, 6, 7]])
print("Matrix A:")
print(A)

# Calculate the pseudo-inverse using NumPy's pinv function
Adagger = np.linalg.pinv(A)
print("Pseudo-inverse of A:")
print(Adagger)

# Calculate A A^\dagger
A_Adagger = A @ Adagger

# Calculate (A A^\dagger)^T
A_Adagger_T = A_Adagger.T
print("(A A^\dagger)^T:")
print(A_Adagger_T)

# Print A A^\dagger for comparison
print("A A^\dagger for comparison:")
print(A_Adagger)

print("A_Adagger does not match A_Adagger_T")

Matrix A:
[[2 3 4]
 [5 6 7]]
Pseudo-inverse of A:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
(A A^\dagger)^T:
[[ 1.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00]]
A A^\dagger for comparison:
[[ 1.0000000e+00  0.0000000e+00]
 [-8.8817842e-16  1.0000000e+00]]
A_Adagger does not match A_Adagger_T


In [11]:
# Define matrix A
A = np.array([[2, 3, 4], [5, 6, 7]])
print("Matrix A:")
print(A)

# Calculate the pseudo-inverse using NumPy's pinv function
Adagger = np.linalg.pinv(A)
print("Pseudo-inverse of A:")
print(Adagger)

# Calculate A^\dagger A
Adagger_A = Adagger @ A

# Calculate (A^\dagger A)^T
Adagger_A_T = Adagger_A.T
print("(A^\dagger A)^T:")
print(Adagger_A_T)

# Print A^\dagger A for comparison
print("A^\dagger A for comparison:")
print(Adagger_A)

print("Adagger_A matches Adagger_A_T")

Matrix A:
[[2 3 4]
 [5 6 7]]
Pseudo-inverse of A:
[[-1.11111111  0.61111111]
 [-0.11111111  0.11111111]
 [ 0.88888889 -0.38888889]]
(A^\dagger A)^T:
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
A^\dagger A for comparison:
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
Adagger_A matches Adagger_A_T


### Q3: Solve systems of linear equations


Consider a system of linear equations:
$$\begin{cases} 
-x_1+3x_2 +4x_3=7 
\\ 3x_1+2x_3=2 \\
4x_1-5x_2 = -4  \end{cases}\tag{1}$$



In [12]:
# Define the matrix A as the coefficients of the linear equations
A = np.array([[-1, 3, 4], [3, 0, 2], [4, -5, 0]])

# Define the vector C as the right-hand side of the linear equations
C = np.array([7, 2, -4])

print("Matrix A:")
print(A)

print("Vector C:")
print(C)

Matrix A:
[[-1  3  4]
 [ 3  0  2]
 [ 4 -5  0]]
Vector C:
[ 7  2 -4]


In [13]:
# Write your code to calculate the solution of the linear equations using the 
# matrix inverse method. Do not directly use np.linalg.solve function.

# Define matrix A as coefficients of the linear equations
A = np.array([[-1, 3, 4], [3, 0, 2], [4, -5, 0]])

# Define vector C as the righthand side of the linear equations
C = np.array([7, 2, -4])

# Calculate inverse of matrix A
A_inv = np.linalg.inv(A)

# Calculate the solution X using matrix inverse method
X = A_inv @ C

print("Solution X:")
print(X)


Solution X:
[-0.13043478  0.69565217  1.19565217]


In [14]:
#we can also use np.linalg.solve function to solve the system of linear equations
X1 = np.linalg.solve(A, C) # write your code to solve the equation with 
            #np.linalg.solve function

print("Solution X1 using np.linalg.solve:")
print(X1)


Solution X1 using np.linalg.solve:
[-0.13043478  0.69565217  1.19565217]


## Q4 Vectors

Write your code to define vectors 

$v1 = [2, 3, -2, 4]$, $v2 = [3, -2, 2, 1]$, and $v3 = [-1, 2, 5, -3]$

In [15]:
v1 = np.array([2, 3, -2, 4]) # write your code to define the vector v1.
v2 = np.array([3, -2, 2, 1]) # write your code to define the vector v2.
v3 = np.array([-1, 2, 5, -3]) # write your code to define the vector v3.

print("Vector v1:")
print(v1)
print("Vector v2:")
print(v2)
print("Vector v3:")
print(v3)

Vector v1:
[ 2  3 -2  4]
Vector v2:
[ 3 -2  2  1]
Vector v3:
[-1  2  5 -3]


# Calculate the dot products of $v1$ and $v2$, $v1$ and $v3$, and $v2$ and $v3$.

# Determine if any pair of them are orthognal. 


In [16]:
v1dotv2 = np.dot(v1, v2) # write your code to calculate the dot product of v1 and v2.
print(v1dotv2)
v2dotv3 = np.dot(v2, v3) # write your code to calculate the dot product of v2 and v3.
print(v2dotv3)
v1dotv3 = np.dot(v1, v3) # write your code to calculate the dot product of v1 and v3.
print(v1dotv3)

orthogonal_v1_v2 = dot_v1_v2 == 0
orthogonal_v2_v3 = dot_v2_v3 == 0
orthogonal_v1_v3 = dot_v1_v3 == 0
print("Are v1 and v2 orthogonal?", orthogonal_v1_v2)
print("Are v2 and v3 orthogonal?", orthogonal_v2_v3)
print("Are v1 and v3 orthogonal?", orthogonal_v1_v3)

0
0
-18


NameError: name 'dot_v1_v2' is not defined

Which pair(s) of $v1$, $v2$, and $v3$ are(is) orthogonal? 

**Write your answer here**
$v1$ & $v2$ and $v1$ & $v3$ are orthogonal pairs.

Write code to calculate the $L_1$, $L_2$, and $L_\infty$ of $v1$. 

In [17]:
norm1_v1 = np.sum(np.abs(v1)) # write your code to calculate the L1 norm of v1.
print("L1 norm of v1:", norm1_v1)
norm2_v1 = np.sqrt(np.sum(v1**2)) # write your code to calculate the L2 norm of v1.
print("L2 norm of v1:", norm2_v1) 
norminf_v1 = np.max(np.abs(v1)) # write your code to calculate the L infinity norm of v1.
print("L∞ norm of v1:", norminf_v1) 

L1 norm of v1: 11
L2 norm of v1: 5.744562646538029
L∞ norm of v1: 4


## Q5: Eigenvalues and Eigenvectors

Let $A = \begin{bmatrix}
2 & 3 & -4 \\
5 & -6 & 7 \\
3 & 2 & 1
\end{bmatrix}$.

Write code to calculate eigenvalues and eigenvectors of $A$

In [18]:
import numpy as np

# Define the matrix A
A = np.array([[2, 3, -4], [5, -6, 7], [3, 2, 1]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of A:")
print(eigenvalues)

print("Eigenvectors of A:")
print(eigenvectors)


Eigenvalues of A:
[ 2.70068584+2.25504479j  2.70068584-2.25504479j -8.40137167+0.j        ]
Eigenvectors of A:
[[-0.0019519 -0.441613j  -0.0019519 +0.441613j   0.31155776+0.j       ]
 [-0.57554325-0.1046112j -0.57554325+0.1046112j -0.94478325+0.j       ]
 [-0.6802798 +0.j        -0.6802798 -0.j         0.10156957+0.j       ]]


In [19]:
import numpy as np

# Define the matrix A
A = np.array([[2, 3, -4], [5, -6, 7], [3, 2, 1]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Extract the eigenvalues and eigenvectors
L1, L2, L3 = eigenvalues
v1, v2, v3 = eigenvectors[:, 0], eigenvectors[:, 1], eigenvectors[:, 2]

# Print the eigenvalues and eigenvectors
print("First eigenvalue (L1) and eigenvector (v1):")
print(L1)
print(v1)

print("Second eigenvalue (L2) and eigenvector (v2):")
print(L2)
print(v2)

print("Third eigenvalue (L3) and eigenvector (v3):")
print(L3)
print(v3)


First eigenvalue (L1) and eigenvector (v1):
(2.7006858365622213+2.255044785097792j)
[-0.0019519 -0.441613j  -0.57554325-0.1046112j -0.6802798 +0.j       ]
Second eigenvalue (L2) and eigenvector (v2):
(2.7006858365622213-2.255044785097792j)
[-0.0019519 +0.441613j  -0.57554325+0.1046112j -0.6802798 -0.j       ]
Third eigenvalue (L3) and eigenvector (v3):
(-8.401371673124446+0j)
[ 0.31155776+0.j -0.94478325+0.j  0.10156957+0.j]


Write code to verify that the eigenvalues and eigenvectores you calculated are correct. You need to verify that:

$A v1 = \lambda v1$. 


In [20]:
import numpy as np

# Define the matrix A
A = np.array([[2, 3, -4], [5, -6, 7], [3, 2, 1]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Extract the eigenvalues and eigenvectors
L1, L2, L3 = eigenvalues
v1, v2, v3 = eigenvectors[:, 0], eigenvectors[:, 1], eigenvectors[:, 2]

# Print A v1
print("A v1:")
print(A @ v1)

# Print L1 v1
print("L1 v1:")
print(L1 * v1)

# Print A v2
print("A v2:")
print(A @ v2)

# Print L2 v2
print("L2 v2:")
print(L2 * v2)

# Print A v3
print("A v3:")
print(A @ v3)

# Print L3 v3
print("L3 v3:")
print(L3 * v3)


A v1:
[ 0.99058562-1.19705961j -1.31845857-1.58039781j -1.83722202-1.53406141j]
L1 v1:
[ 0.99058562-1.19705961j -1.31845857-1.58039781j -1.83722202-1.53406141j]
A v2:
[ 0.99058562+1.19705961j -1.31845857+1.58039781j -1.83722202+1.53406141j]
L2 v2:
[ 0.99058562+1.19705961j -1.31845857+1.58039781j -1.83722202+1.53406141j]
A v3:
[-2.6175125 +0.j  7.93747523+0.j -0.85332367+0.j]
L3 v3:
[-2.6175125 +0.j  7.93747523-0.j -0.85332367+0.j]
